package engines

import (
	"fmt"
	"time"

	"neuroedge/kernel/types"
)

type TaskEmissionEngine struct {
	Name     string
	EventBus *types.EventBus
}

func NewTaskEmissionEngine(bus *types.EventBus) *TaskEmissionEngine {
	return &TaskEmissionEngine{
		Name:     "TaskEmissionEngine",
		EventBus: bus,
	}
}

// Start begins the task emission loop
func (e *TaskEmissionEngine) Start() {
	fmt.Println(e.Name, "initializing...")

	go func() {
		for {
			time.Sleep(3 * time.Second)
			e.EventBus.Publish(types.Event{
				Name: "TaskEvent",
				Data: "Sample task generated by TaskEmissionEngine",
			})
			fmt.Println("[TaskEmissionEngine] Task emitted")
		}
	}()
}

// Stop gracefully shuts down the engine
func (e *TaskEmissionEngine) Stop() {
	fmt.Println(e.Name, "shutting down.")
}
