// kernel/engines/task_emission_engine.go
package engines

import (
	"fmt"
	"sync"
	"time"

	"neuroedge/kernel/types"
)

type TaskEmissionEngine struct {
	engineName string
	EventBus   *types.EventBus
	stopCh     chan struct{}
	stopOnce   sync.Once
}

func NewTaskEmissionEngine(bus *types.EventBus) *TaskEmissionEngine {
	return &TaskEmissionEngine{
		engineName: "TaskEmissionEngine",
		EventBus:   bus,
		stopCh:     make(chan struct{}),
	}
}

func (e *TaskEmissionEngine) Name() string {
	return e.engineName
}

func (e *TaskEmissionEngine) Start() {
	fmt.Println(e.Name(), "initializing...")

	go func() {
		ticker := time.NewTicker(10 * time.Second)
		defer ticker.Stop()

		for {
			select {
			case <-ticker.C:
				e.EventBus.Publish(types.Event{
					Name:   "TaskEvent",
					Data:   "Sample task generated by TaskEmissionEngine",
					Source: e.Name(),
				})
				fmt.Println("[TaskEmissionEngine] Task emitted")
			case <-e.stopCh:
				fmt.Println("[TaskEmissionEngine] stopped")
				return
			}
		}
	}()
}

func (e *TaskEmissionEngine) Stop() {
	e.stopOnce.Do(func() {
		close(e.stopCh)
	})
	fmt.Println(e.Name(), "shutting down.")
}
