import { EventBus } from "../core/event_bus";
import { ExecutionIntent } from "../core/intent";
import { v4 as uuidv4 } from "uuid";

export class MLIntentProposer {
  constructor(private bus: EventBus) {}

  // Propose a command with reasoning and risk evaluation
  proposeCommand(command: string, args?: string[], reason?: string) {
    const intent: ExecutionIntent = {
      id: uuidv4(),
      command,
      args,
      reason: reason || "Generated by ML reasoning",
      riskLevel: this.evaluateRisk(command),
      affectsSystem: this.affectsSystem(command),
    };

    // Emit to floating chat / approval layer
    this.bus.emit("ml:intent_proposed", intent);
    console.log(`🧠 ML proposed intent: ${intent.command} (${intent.id})`);
  }

  private evaluateRisk(command: string): "low" | "medium" | "high" {
    if (command.includes("rm") || command.includes("sudo")) return "high";
    if (command.includes("npm") || command.includes("yarn")) return "medium";
    return "low";
  }

  private affectsSystem(command: string): boolean {
    return command.includes("system") || command.includes("service");
  }
  }
